language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
env:
  - secure: "c6Fp+oohs7/VbDlWcuLKm1RNrUQ+MypzLPQmz+E+UFcRyZ+uPbUkhWYz5YKDj0rDYc14Vdd2EzxkW//jckm+Vnuwm0EOPh23Vs4uFT9T8AdU9rivYcPuls++fWnMFj74lIY75IW4eE1gBcoJoHPJ+kD8RxSv2Zlu8E9aJIib87xa5NOFRKVGPfAT5hwgQqnIK7cuvnxVVx0P6Z0EYlGuyw3FhUKb/HS0mKseq6kjSHvUzwR1KlxBONzYq59csqxX2/JbISZ8pyOSPl+c/qAgJrFHuZTu6+NxteP+wzAnx1gUuRxfAk2lZcFm7xjo3yr5WeQsFCnOQVsyv8DNLM61qvmkNnfWddeFyYZDoSTbylUe70l2PQgx2ub1ZbnzirSY75TKf6tIVGkD80qbpycTwj3bltfR44OwT6SN/JkRQcoyXGE1kjX9TRWvkbry4si/8GeBTimkohmy8P1gQ8rITIC2tGM1ipBy0kQGXBxqqYVhbBVJfIJ4e5Ali/ExZcETWwy8OHGZ7exlgXi07FLCnCo4NGwAKP7YIDqcr3+ofnYFlzE//G2SIZDL69Trir7Gd1VES3LCVb442vai3qlaAOk30k7cVUxrF7iub5sSQWYEzJO8sz8O+k8uw8jkBYm4I31Zpqh2GUb7Hjv36X2eTnVw+5mnMqvvJrCTA7ACE3w="
    secure: "TDymKzVOK89KWd5eLA+vJ9cW+fGKFkj52rlAQtr7Xgci47OdLYQuBg6+Xcp0TOwvv45RpO/oNZ0X2S/syb6WEuPfLImgVPBjKczn7VoiAVbhtazKQ173Av9tvdICvLDkPJBjGQdbTlKVWjtj5WYSeJfrMr2WIboblRRNJgUOFdNQDj0a2GeYNXBiUD+xWAEwPHLx0xWPuAWYOG66O22sseS8bKlmD9Qk4ktnZpguELLmv6Dzw9Wq6581QHqZYCE6W/O5Uy/dOg293qgHpbyxtFcHDua3x1rlu0U39yvJm2E0ygy3aRBjJJJR5aa35f30hFC2/gRtNyXwEGYLELK/AyVyEvqOiqQrUnCWcaLaJ1qLP6U5auoqHR9uEy7mhi/ICGL601loA5y96YsLOIla62wervy/3vvqzOEaSQKDqOEkxBlTmHlwTR8vFtdQSXYeYVXUSud/mxdiOLm70RB+QxCB9Q0ifC7XyWbmYFmIn/xEKsV64bXSksDmQOH6DmB0aR525kEoQEemmO7/EaLohQ65cOF4eVNdtRQZOgaFo70+d+fXsNba24jxb97Nv9xEWPXdSaEpeUc4X3X95bgic7jTwnxmQuCmq2EjZF2B+ZH6Ny0+7OS7E4h+Qz7kuNgP3uqk3ocdfXknNBqxDfa7EDIFDBDGHpRESySTzjATHWk="
    secure: "tlBkuQQx5v2M0k2svGh2ytWKHKrADFLG1ZkARMErw52TfAIep98qLEYl3Tym8juX0VRRE7vXRBYGrjsFQhgEEkHYxZZlGcjgLzCBxaVu1QhgNOo3VALpOftH4MfOCakTIO++1YmSNYyWaUQmbNHm5Yu7x2+0i4A82AujzaGkicTnzVvYLicirnS6rc+ZCHVQ6lfDJ69EtmjaYiFbwr3oCHMjaWrvKedFWcZ8BMIbbGMGZopO0JuNdnZxeTMUZRlqBw8+XtI/JdOIDTsCGIFlCwiDiw1psmj1W8PV5iI4KyKhiUNOXqv5vMIYmdMaJaE3sRT+gk+o/ZMrkp9jnXh0nLzfP/rSIYUSo/tEYlLp/kBPgyfUyUq6CAgx19wGv4P3/iZ8zH33h+FdjBRi1OKwrAREnJZSZX8aoDuihhvI1G4L+2pj/lGsxwjMsZt3uqBPlroyEHsTJCiz1gMA4oAInPsj66lZkM7ot8Fa11FZiBEKRjREuMA5onyu2wy0MvmLs4gG1RXFHaRSMfvzDx9zcSrb7Gqg2DgkyTk6UYQFM+qbgAnmVYhi0ItG13P/x8x1n+++b2hy3LV2XbAgCzmkp1LfLKNWX6Qn797Wuefx1orh6ePT1P77r7TwKzaCaHKY7uFUjEROwa/Zuo25fxOP7EpkA2u6NlJaj3lAKka1hF4="
before_install:
- sudo apt-get install -y curl tar
export: role='arn:aws:iam::581647696645:role/tx_lambda_function'
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls

