language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
env:
  - secure: "nzOhgXZoV6Zx2kJCPkOTo5xA+WDbXMYSBu2XLs3d7lYsa/62qCh+oyBJyriU5ptjNxbak4olJgUZYGJ4FLk7ND5RHXX+5i+6LnNesDbMxzViTBYFLU+mIBJApPVl1zx2zWJ8LWpyE6idZJPWsKP2nK+aNxkeCVSPixdovX6p8DGjllh2xNxQLKomK93GnFkhGNmOxxnSjR4u4ybEVV39msll9qj4eK7ZLUT6EPFKksZRAhcombV/VtmaLwdaqfDVgduJ7CsQnBQPT4Dp+ULnjlKV5RzXiFWkdGvBSXLWTzW3KoF37WyBOzbvo5MpjW8nwkgfm22AK2Wi3559bQCx3IqJulT9+/aolGEEZjJq+zXD0Sx8v0HCStSb+6q2peTFVirjE4stcR5mUYsEfJaJWAS+wFJEslCC3fh+Vrp5h4yzJ3LkeRsX8+1kZTPt9CiFc/JaKh8n2A+yorSeQdLBm+mr7PE7Q2cRdxmeU2s5fwmIx/u7z9zRlQNlpSybiKDBCT66qIJWH8kYCKpQfWhHfyWvgh2Yp8RowW6EaKNyeUd24Qf3Ob1m0cM9b15xOo4iSBmg6cvWAoHEUVJHGGxo7cOJrfTlD02h2ldyri0OvqfXkf4JQDlASX5RnprwhjXr8MWZMhiWcGJlMbxY430IxJM5AYeleEadVRUF6H3/6hQ="
    secure: "wSZ/n73iKcamDHIXJyFiRJ4Tp/Afl9VxCBTBqCyrA8B/rbPFYAjO+BkqPalsMLAgYChqDLCRqkcvBmN906bitkGtj6eC/Y/N1VJARYuZ4MVW7/84Aya65EiIPf1C2Qku3lzZyzbvbdwCfLQNx8Tal21OL2QLiEDbGIybLdSjQw8VZ7WdUG2YXP4TcbUKkm3bMv4d+PyXipAU7E6AuYV9QJFjQQrlbtXA7OztYVLIsddYrlnVXQuY0twvv2Ksy+FjrPFOPDiTmzlI/EZsiTguPiF8lhRl5vVL40cPKFaDnP15HOSMedRxPUmafQwMmCTxknx2HBIo6AjPM5BpPICsdVh/TQM/tWmGnrd84OMqB8F6ML73XIQdekW6NUaQ7wQcH9RAPPYkAAGacYXutssNCFOBF6wySkZ+mzzjLBQBEFZZ04mV0ndZ9l7Jo/P3G0bNeIYhVi9r3Mx6+zq//5YTYPv1c4KSJSjqy85R2DDLW8drJj7DQKabsuGVVEeBwmt8mHqGrgwpmdQZ6f2h+RJ1gGaS7sfZl5PbsMCHhdK118h1hNXFCnMCI2rBg9mZloRXqMo6sD42spzifhJdeMsTl63auVCAnNXNbC/GofGoM0erjnW0Nqs58PNYHJ515FJkiWEzZVsd9gLzPQ4FsTAfZnbiSVVLcyKldQM6Olyx3Io="
before_install:
- sudo apt-get install -y curl tar
export: role='arn:aws:iam::581647696645:role/tx_lambda_function'
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls

