language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
before_install:
- sudo apt-get install -y curl tar
export: role='arn:aws:iam::581647696645:role/tx_lambda_function'
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls
env:
AWS_ACCESS_KEY_ID:
  secure: CZIobUlLQ7EHS995qyzs4fA7DAWELEElc/RhkZNi4jSTP3TTSQQ/GFPHXsoRgpP9jXOCxvQNmg2zOKxetL2lAmp9N96syuJnOSu3+KyfZS97uSB/t11RTnw8nAKJg+L541K1bDs6BUjCdRq0r9l/0vntp+x4EIhI+T0V+iC7tyuXMsiTniCSMEhbvcGtmJn2Q0bf2tr6xaVWhJ7a8z+Nsv1iF3kKF6HoFnZcgUtbPt8LHz28qNpvIU+d36PEVJDRi0CD/TklDKPmm80PQPipRSCPFmIzebHvziMykjJYVBHRwYE58dtTLFv05mbCMWMp5FYJRF3DCWkHpQgLGnwfye6Yr6bvwcTCgund/iCyvXawWrj/mTasodS1sDB2TShg2mCei9uSRrJzBgHpc6+o4U5AvEdcX740P83EvaJgqEf5j3F96uvZARxKrUnVlE2UX4SdJ3xR2UO1rj4ft+6ChIQBf724gPkOH9lGIjCWabYGM6mZVe4kxerReyCY+Rr+qwjOKYD+oQEwYExE0+snrfAHDWps3NBmypA+lE0nEiEhXrZKl5Z7Syz8+VeC11/wu5d77NSsYYTpWPZ+3ttVCP8da5OiAaavqo96quqJAIZnOkThubvvnE+8esoKGZysgi0h6iaRFNHp1qUOQb2/ss49q5couFkUdnFUmoOuav8=
AWS_SECRET_ACCESS_KEY=:
  secure: LzIGba1FBKMBQS/h5pWqIhFGHQSWO6y18Ek9tdEHa/g6Mf9w/0RhSI2aqBqRAShsvSLbgjCVeWOg4D0JTDdn+WWC7ob2q5IRTBIOJJp1PjXgAVJoR0rOXRN/NTnakgBa4/BR9sLEJueCQYDcys8RexbxGxl9R8MW2k1XWoIbG2SZVEdqZ6RCLu6zbRs5FpfsMlJVD7BwDglXKXC1tt6oLpK3kCFz90zIY/aljtsHOo3TC+2VsgJcls42QD6EBTMCp4QWRHargauQHmoyidh9wkqzs0+iouYNlBfvmq3jKV22G3O8E1CP2h7k94Cn9npwcO51VuxlfJXidtrDDzo+fe9ZXOYNPclbF1TKo7DXQ52IFSFifuZ/GjPArC2z1MfLIZo7VS8EThZXBvgMv4orQGoZ+berk378xksoSkp9RIC8W7Qza0XFLTjka1IkWFQI821td78mZQzkSA5SbQYv5BwkTUPi4gRRwXhhFoqZLEf9IYquphkvUybPIIUG7hTmbGBURVvyFrcBEmvcSVwqu1gNXFGVQOaispSICHjxZKRU+LXKKY7Zm3g44Fme/+uFlNu7JcF+i4EAdTJrl+OOM03OemZIopw4WPIi5pM2crI4kT1U46NsavtA7ulcG+u72wDP+HqKHhjGbl6piCWV7Nt1wyx/qZxnmejxVYkHxGg=
