language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
before_install:
- sudo apt-get install -y curl tar
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls
env:
  global: 
    - secure: "NpRLqoT/rrvTwc7fHoZTsOQ0A0mv6KmAfgXdHtXwr5TFSvdl00fjjkyeva4Gz9fIYCeSdZ5jqMFRGDexgYJsF+0/CONS7onPe0ZhHs7WV7IAdlmsD7eOOA+GfuUaPZoh6AnPdC4162+iJRTAHctVjRZ48mU1bKBBerDwHNL8kxMctSPi4lPOn+vckKdRnjuok+KGthkQiatsUA6rWg+BCs+MF1BCjG26Fre5sF5XwnkKm6DJHb9GK2+kl79mvKpYhpXfmRh5p5/9xlu6i9qUS1S+dX3eQGaxkFP/iiMhkT2rU/efQpXSuTp3E3I8/2AuR6gs0nQ3z1I7LvMMU+PCfWH9uFKhOrFc5/DnWdUF0xys2qzlspwr171AzjuG1SIlw3ujMz6aAdRC/WRvfYV5yI+aMxwwDp6ZXotKV/dU5eDxXdREkyKFwyIePOYZiQLnNwm0rc+f737p+z7dcRwKaGmiJsxcmNzJUUEduucC91CxMg1Cj8e5R7DnrYp7/vFA3fVTFJmf3tktC7WnC5vh5DpnUbiwxIaQw4LkDIllssTQydXycJtBJAXHDOafWm5+zja5viByjFAHjQZnyictMZ2Nwz0t0u42fL1YIVTOGWaJmYxGzFkwHNmD5VCSmncKFLicfCXVS8PATVTg7dBPoy15ggVN5MywBAaFHKMRN40="
