language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
before_install:
- sudo apt-get install -y curl tar
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls
env:
  global: 
    - secure: "MwCLdSjJ4yzyj7LCAMEvU11yoGwvRqFZYUEe3EZvoof87ealAECDBdFjdtrPOz7+9tjmf9MoVHlsILlyDD7CfGr7BZ2Kj/KbMZT+/JKhJmKuMfr8eF3ntaCA0+/ARnraHCJPa4Nh4yCQ+mAfjbNlOYYWA6woXJYG1zfFGp1MLOmz/h3RyBmk/v3jai0fcK5vT8xEzkwvOXIFdv2EL+vGvH/+w04iUhv85HjV3KTJYGVnnXPjVfS49qEnn/rnfNfm63TWpLpoKdzEGFMnaIeRAqRDw9+PxyjQpQcYNISgr28TOCalRtPClrXTQi88BP+4H6jrnoKtpBdhyGkwS0/blfbDLAULDYoADO+98iHfEHSRfxSDWolCaXhpBNJ6nHHhCfgChsxtO3xs4dpzJ8q43rQjqVkK3dxpUO3FqVDWX6hyBBcdvOBu55Uo/i9dwVxsfATU/5DEq18iyem1vBqTQy293oso1suvmG3c7UTeuNuFU43gxXnzvYvFlk4n5EywLoXI31am0ixDzHRyt0P2kX3U6x5vm2D7aIA7H+VsjXILlO4xXf1M2O/GCcYnJNNwHCn+66H5Np3RH6+byyeWDuf1oOVzOJbg6CbO8uHcPGNHlGhRZIf33NLhNMsj4Cd0WNYwiFdyjMfTfcXf7OKHT1hm2a09mvGKL841KyO4Qdc="

#    - secure: 'IQcqDRBwZeD2FAz3J3BtVsFSsBX6RX3inw8OpkFfcu3NFdNPOjOdMU6H3c7hog54L5aBcVrnY9q2dka1QFOLPlD/Be9HgPNivPvqUQ2MaC9mlwr7M8Jba+rUg+OBERqpFgSQtu7ZlMn+ftE6ihP1DASpvcF5T41UOXBUzK5RCRuu49AjReXCXH5UWfAUIybBsYwM3GN4+DgpgaUuCjQ6ITCHqdKOgHG7FRutdWBm1RUHvWifryXR/+7tZHwte57a9BRAoi9Q0x02hEAN9DGhCdw02wbiwQ/c8QCgI4yuWd5onTg6GKs5EvBD63zzyJWX6MnvIshkbltX+oE6qkOGOfZoyufw6nKwonD4FWbP+jFzGNLpeKRqqI0iX3n+9Lau9DMD+aaCpJXEKXjZ+jWJPGTaB2fk/lHG8e0uhJVGUlFh8UDyvkAaSBwCNGxD6my4m4x0oKJ2yBrLlmqtZQJvbJavgBbAk1ySWea/bXFBHM6AnqJ7v4WiK/ttZvWqiIKVAvwNuV2FBSZ03RHWpkzWBgchwAUi+uBpZuTQcQZkdFXNrSsG2Qz/HEajykTZwF+2Ybd7m9NxC5fsdvlaeoBrR8biJR4DR4Uab385+EzOboUklOlADcwdrYeWCdr9a/9PMpaJaRd2wHKgNivCkqqoVFlVnjTUXCOgQZGzS7vzMdc='
#    - secure: 'SfRAEBTwdYUQziipdtaFa2kE/Rb7toFWdlgxvql3VecBnov0aIimtQfD5hA6OVgOPsRRiNk06tN0D4Zk98uSSwUCEYdDbuF/QSNCaauXjRn5jymNEWwqjyy2JvGbPSZ/CB069CvlLnwHH09yA5c794KK8XNvO/Lywuk2XE9VDxazvXzGJfDeSeEOOZ9g0xBFi0T20Py3fAE4dR1f9JOJ4rMSEcBZVzAVDI0Yup4qbdRSs81Q6rkF+8B211SXjcREo1OqYwi+lKpeC5T3IeDYwNoJj3owwhLt674PPpEhrkw+wBNcJSYmyOLqVQF90O8m/qGHEUFcy2irtUxy8/OQFLKSppReNBA2sau9o4b8PGiVK5+or4pWdTJGLONiBSVC+JchUbNzhQNlueQPE9KIvLiBEAuiiEo2LsEXMWIDeZlurblsx3FR8jQRUYFIP0op535jwDA6uex+qyi5OIuLBWpfMpcgFapry+ouYmDiIoq/FrPdaYoyCZeq3///O6VJ4F/CJSbN8I5mK3Tz3Zj0EHeUoCT7zV8ASNml/yS2rKk7sEEUzuxAPqoo1YzJxHi9mJLX4jSr8eUMLs6K1Svvvp/+7tRD5XEGooGB/veAXCqeH6hyi+yot+yZSgjudauYYFW4Ulv0VTbvlF5sMW5x/GrI1SXHymebycl0KRREi6Y='

