language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
before_install:
- sudo apt-get install -y curl tar
export: role='arn:aws:iam::581647696645:role/tx_lambda_function'
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls
env:
  global:
  - secure: t08K38h6VPYjfB7TnloCfmukZoQgFlTJxq2t5YElXhJAUckZ2KOsgBmOaqngeWImilRKvWi50Zm3ZlgtzoG7PWTN3zvOSzSXsIYcO3samJi05qkRMTDR8CfQpkBY5UZh2Q7EA3ZYp4pk/KQ85wdMzTGcnvRptSBbITObhcJFvMiVrvkYLoV+XeBjmXzvtBVSrLO6YvC8rD2M4q6Z/4FXlwP5Wf2eg0KvWWG7McRA2WKLO9MDk2E2sde/Ecm7Pbejyg6grxUc/P8zHeHGuU8kyfZ44AyZDkMQB6cYTblxvbZqpHKNdPf6kXeTT7UL3DTwz+2aU7nzDEEcJ6C8ynuozSLRBAi5uVKVWF9lsmW3oIunibcoDWLcLGGT84TObv1tXRacLxQ12eFhl4Rjop79Ed/a/PL3inxZcDwjD6VQSWgNs5U56VmZIaRaPJKWHoqLsZO0in6w8J+p34vTNvJUJ0q54+lBfR7ISXj65uWE9ROZh95Ag5BEPPcd5fDBu0ZGrilJEdrvn5pJc+x+P58Tu99SJsN1n3NYcJBuY5wXrMzfhGtp7LNDTMh8Us/z5JtLKmt421rMyVcwuMU1557XjJ0CUImpRYb4TarBqvbjfIG4xP+RL2RfowA4JZopp+Q8RSFlN/k4Qgg0TnfTj7FlNSP185KWKxZqtUx0875zmPA=
  - secure: d8fHdOZH2eh7Sh3R1nMRW5iqgYRx71cFwMhKGVzh7KP20khnJTHDEYjoJR12U1i9O6gfkFzNBZS2TRNqh+PnKae0hffuhUaXA0b7HRx3/Ib2/NrWXbAkG+JeZNyb/9IqHxINgYLzbgT1GhXHE28pzSk2cJ3grDRNR1yN51Rr0hgHXRqaMicMI+33g5G/xCk3QkDUMKHVkzKvvm6k+9/zo5wexpC2O59MbWB7Y0VWxx4zYCeJbz6D7mITSpuLGpKFKzxuHAzjMv0MBK0Rt2daoB6KTka8h+v/O8GGyk52Yr4htfDPxqljwAuli+jKEa7pPiG2M+Dp96rlEMkqrylw2qx0uvo0bu5Z9bMI8fSjtVn6PRP57WgoemKrNVk35TrRmQ4Ss/0+0UKn1dlXorjDRv1+YZjZFT1YMcwhWI3NVjxahrabLvjYa1aZiQQAlQLtQZz0WCJJhm4wRdzRR26hPM9FYTzgFi2V2+a7w9ZjrVTv/qLXtFRXOcUHeYwG7fILGJfxc3Qi0fy+U3VAyckuk1Ot3269IumhSx+Ke1I9I958CzSFbS/EGfg7Rq844inAcRCx0jXA3Ss9nZKpvRXYlHYet4htLtD0pK0ojl6/8f25JrHYtqxizl6d1krhi0o6yySYQag+WbTLczdlF21oSHIKjTHwf5nuw7xfen3ngkM=
  - aws_access_key_id: ***REMOVED***
  - aws_secret_access_key: ***REMOVED***
  - access_key_id: ''
  - secret_access_key: ''
aws_access_key_id:
  secure: wU+tVcWfZLHAQVzWOLbEtkswV/VEPZMWFIXnGeCM+3BemnLjTsDyVSPKgzLFe/o1c4dgOO+7xCi/EohAYJCT5/4bspY3iFgoG99y6aUDxSXmeq9cOppBb9+io0FosYoilvR+X+TSuBIkwv1Sa2VbqB4aA/anm/VHEhozajAQEhNCLDLdZiE2NFVHtpDvVa9Sp6hY0Pc1DaEifoIaP/I5vjE99q1n8jwnowMc/vmsigEQDDmk+5nqs6GeSQpjEBMskpYaqZQZgSUi2/TZXrc+ZPL4ppmlk+BfasnAIQrDLKJxiRnqgg92+RC1t9rR7bwzkKv2aQ0YdgL0RC/AiY47GzLrEHk1PxGEVfzLE7DuVMdwLv1mTjRBz5AgLlyGEGjhV9O7vJAdRZATCVT41fscp0Ce3zT6NOYi7v4390YCtP8Vq3AjmfvOlVlZd3hqM+OLr2ziR7ngdarGBOnoLAs2IH476Ia0YVNr3yZdWmqgjGwpbit8baXcc34/92c37dlZsz+7Mi6PcSWlPCZZsiJg5oSd9kO/55mjsHVQmXPmQy9pHA5a7tgmfxMsb1hnwLP4pA4YPUy8MbsBJVpZnE9UEKLp/BVENVgYyXNCT2BHvSQAr8gTWLmFmlFCD5J1ym6pi2HjVHEk2BdKg+hBYKgiQYCOL2ibF3G/UNI7yHDZt/A=
aws_secret_access_key:
  secure: znjJoyVkag/2ht1qt1NYiUFI/6rFyOFocE/m4LDBC7LLlNY0y6WBhFTKbM2ZzI4UNhRhBzh/zoFqk8UsqsjZskelRL1W91zs8OouASMDl4VlR0E4u4TlZmsR39wCrl7nvVT3xeFDZr3ifAfmKP7WoD8C8x+tTMePm/jRZzjg4szGyfAZAPp88n7dgLV978JNHHV+nw7ifWhRCajWS0Vc4KVk/LABVDTL5qnfAyvt7ra0rbP2LYRpDMRcosBaxfeqs4IVzier2cW03IwH1YTosIJu/QRKnaee5ablk6yM1pKsCfmNskjANBNy9NFRDf+5MT/F64BtBQ3INP76CcZoRsNc+JB7fdQ/U/mhuoKIJwZHNXXY9aw6N6MWKIVhWCCYJNIC1beskF/5PFJQhk0x3kOWtxsnoL4fIXEOolVLmZIvmYsU/raV4iEEuwpI+AgnLca2PC4NKZ0zlNEHq0d8a1oAJISMHUj0GKujZ0XWmxI7g4UpCfPcJL5/f8dmqI3jyQIjb9GteDZ8hIC+zya0XZzxkkVPOOiS9Hz9BZykWHTI13qQ8noNYiOqrlKhYzddPAvfMLzCoM0tupwWlUxiir99fG42JbXpR6LYJAy/R4RBnYYpdPhwmejpO0Cf1m3p3OAPYvbYBaZ/RY+FMxZHVdWQx6BuMsQWXHMQOO07KQg=
