language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
before_install:
- sudo apt-get install -y curl tar
export: role='arn:aws:iam::581647696645:role/tx_lambda_function'
install:
- pip install -r requirements.txt
- pip install coveralls
script: sh test.sh
after_success: coveralls

env:
 - secure: "fVZ010mlmj9SV1D2WeH40nVp8EQsF9xeZYc2Jf3QLE85Z3lhfeyWILQMmRGDSUYOx8EQaWWlWwEKQ27SgB7JCnYABVMPkyXUX61cd3GmS3CxKP3+h7c5qJd4UWtG9Hzp6r0Ck/0uLOW4kvs5HZ8+5NoqlGq+pF7Xc6wxfbx8+okwPlVq1U4+Xbda12WEKyK0XcVzxzpWTVzi3TmS4cJ9LM95RJj8aWdEIPH59nwjrGZsPPortxvax123C3NOp+9i8uf8MF+LHXX/6II2RcsqX+zeXYQd7m0zuzJFNyp4xaiDyiSr5iM1dVQwZRRvQ0AbORdOERCPaGNM3TdVgmu6ivR9eJ9KPapKP/es19zLF4wn9Cj5MFP9gpnApji3gYb10xlRvbU3xzkALy6+/7APIR7R08bOMZDLeEMnexobBrzPPteOzgSsHTUBXYkIslORm2mrF8euhN0AdKydsXsNsOpQjesNrb9SQEESM/QWgr/RN8jNa5wc04Vgo0Vnql7Zp8lzvwYiTx+DRfjg2H8ttxsAUWa5dzpDVllUBS3/3Z7eO6A+DIOTzW/c22TYw5hxTTOSAg3TvgLqX1B+UWH4M5n6Qrmsxg2sftRtGIHGhjVJ80JPEiF2u6l8CkiyiDDoA5AI8yr1mEx9j2TrGCDlFPEvhl9D3rOCjhlu1fnKFjg="
   secure: "FN0ilK3b1PqZPprgv4QoAeYVKahNC3+17fp0TweTjCxvfXonr7D/5XxSdMb2szFryqdtSys8YpOY9CXztbk9BpLD1zmW/q3xJdZC/awbBvAaIEPCG6tQliznN9MfN9YRVUT8rz/O3U6IJcvtCoRWLJCBGvMy+nEDOhaNLF95ZiD32kCLYkiyouSjlc65mIV/RMPAx3/pxDHv5fct7VmZkOP8j6xSXuYwvB0XcwjjMoMSktAkS5yKjcFty5+CgyiwJory6l6P0cExK+3RSf+FM5ueyY0PJGBKwrRYGhBiSkOcyO1UjhHfUJfQVtodjVuQqXdlpq0M1+YUU/JcJxb4Q6pJNiSqwvnZyiPK4C7jJHUsmB+lVFBPe3hypjpVk1W8cM35nzMutprUM/JI8WWPxEIx08D+39hvORqrcjH3oSJyLq7G+7gZVW0XpCsrqYkSqxHy1ai/s/ueSXAFS6qXZF5YQJfpuXXQLyWwjBokOUt+hOYuLXEjkWqUXb2yI9pI6yDkrvtUHRpKTA2v+4GEB1xUkLA53ZLVel8uBuQxLnXiT91M+XeIoJiG5Xx/L1FHGLv3+yBN4TFI1AfYYu/IbEPjsCEuaIQRKz2XokDNbPi4djQNQizdi4zGc5pzIOpBeHGAltQuhdbZneYvxXvxugqxNLUCwgayPprNYAsJsYI="

